### ISSUE TITLE
Error initialising model with weights

### ISSUE THREAD

**Issue by M3GUMI** [zyyan4/ml-clap#1]
I have the following problem when initialising the model with the weights from the pt file on https://zenodo.org/records/13358171. The version of torch I use is 2.2.2. Has anyone else had this problem?

/home/linux-console/anaconda3/envs/FreeVC/bin/python /dataset/megumi/code/clap/infer.py -c config/ac_finetune_le_mixture_infer.yaml 
Using the cached tokenizer of text_sonar_basic_encoder. Set `force` to `True` to download again.
Using the cached checkpoint of text_sonar_basic_encoder. Set `force` to `True` to download again.
Traceback (most recent call last):
  File "/dataset/megumi/code/clap/infer.py", line 135, in <module>
    main()
  File "/dataset/megumi/code/clap/infer.py", line 119, in main
    infer = Infer(config)
  File "/dataset/megumi/code/clap/infer.py", line 52, in __init__
    self.init_model(config.infer_path)
  File "/dataset/megumi/code/clap/infer.py", line 60, in init_model
    state_dict = torch.load(checkpoint, map_location=self.device)
  File "/home/linux-console/anaconda3/envs/FreeVC/lib/python3.10/site-packages/torch/serialization.py", line 1026, in load
    return _load(opened_zipfile,
  File "/home/linux-console/anaconda3/envs/FreeVC/lib/python3.10/site-packages/torch/serialization.py", line 1438, in _load
    result = unpickler.load()
TypeError: Can't instantiate abstract class Embedding with abstract method forward

Process finished with exit code 1

**Comment by jimbozhang** [comment]
Hi @M3GUMI, we've updated the pre-trained checkpoints. Could you please update to the latest version of ml-clap and try again?
